# Beyond

> "End? No, the journey doesn't end here."
>
> --- **J.R.R. Tolkien**

After reading this chapter you will be able to:

- Understand the roadmap to continued education about models and the `R` programming language.

## What's Next

So you've completed STAT 420, where do you go from here? Now that you understand the basics of linear modeling, there is a wide world of applied statistics waiting to be explored. We'll briefly detail some resources and discuss how they relate to what you have learned in STAT 420.

## RStudio

RStudio has recently released version 1.0! This is exciting for a number of reason, especially the release of <a href="http://rmarkdown.rstudio.com/r_notebooks.html" target="_blank">`R` Notebooks</a>. `R` Notebooks combine the RMarkdown you have already learned with the ability to work interactively.

## Tidy Data

In this textbook, much of the data we have seen has been nice and tidy. It was rectangular where each row is an observation and each column is a variable. This is not always the case! Many packages have been developed to deal with data, and force it into a nice format, which is called <a href="http://vita.had.co.nz/papers/tidy-data.pdf" target="_blank">tidy data</a>, that we can then use for modeling. Often during analysis, this is where a large portion of your time will be spent.

The `R` community has started to call this collection of packages the <a href="http://tidyverse.org/" target="_blank">Tidyverse</a>. It was once called the Hadleyverse, as <a href="http://hadley.nz/" target="_blank">Hadley Wickham</a> has authored so many of the packages. Hadley is writing a book called <a href="http://r4ds.had.co.nz/" target="_blank">`R` for Data Science</a> which describes the use of many of these packages. (And also how to use some to make the modeling process better!) This book is a great starting point for diving deeper into the `R` community. The two main packages are <a href="https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html" target="_blank">`dplyr`</a> and <a href="https://blog.rstudio.org/2014/07/22/introducing-tidyr/" target="_blank">`tidyr`</a> both of which are used internally in RStudio.

## Visualization

In this course, we have mostly used the base plotting methods in `R`. When working with tidy data, many users prefer to use the <a href="http://ggplot2.org/" target="_blank">`ggplot2`</a> package, also developed by Hadley Wickham. RStudio provides a rather detailed <a href="https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf" target="_blank">"cheat sheet"</a> for working with `ggplot2`. The community maintains a <a href="http://www.r-graph-gallery.com/portfolio/ggplot2-package/" target="_blank">graph gallery</a> of examples.

Use of the <a href="https://support.rstudio.com/hc/en-us/articles/200551906-Interactive-Plotting-with-Manipulate" target="_blank">`manipulate` package</a> with RStudio gives the ability to quickly change a static graphic to become interactive.

## Web Applications

RStudio has made it incredible easy to create data products through the use of <a href="https://shiny.rstudio.com/" target="_blank">Shiny</a>, which allows for the creation of web applications with `R`. RStudio maintains an ever-growing <a href="http://shiny.rstudio.com/tutorial/" target="_blank">tutorial</a> and <a href="https://shiny.rstudio.com/gallery/" target="_blank">gallery</a> of examples.

## Experimental Design

In the ANOVA chapter, we briefly discussed experimental design. This topic could easily be its own class, and is currently an area of revitalized interest with the rise of <a href="https://en.wikipedia.org/wiki/A/B_testing" target="_blank">A/B testing.</a> Two more classic statistical references include *Statistics for Experimenters* by Box, Hunter, and Hunter as well as *Design and Analysis of Experiments* by Douglas Montgomery. There are several `R` packages for design of experiments, list in the <a href="https://cran.r-project.org/web/views/ExperimentalDesign.html" target="_blank">CRAN Task View</a>.

## Machine Learning

Using models for prediction is the key focus of machine learning. There are many methods, each with its own package, however `R` has a wonderful package called <a href="http://topepo.github.io/caret/index.html" target="_blank">`caret`, *Classification And REgression Training*,</a> which provides a unified interface to training these models. It also contains various utilities for data processing and visualization that are useful for predictive modeling. 

*Applied Predictive Modeling* by Max Kuhn, the author of the `caret` package is a good general resource for predictive modeling, which obviously utilizes `R`. <a href="http://www-bcf.usc.edu/~gareth/ISL/" target="_blank">*An Introduction to Statistical Learning*</a> by James, Witten, Hastie, and Tibshirani is a gentle introduction to machine learning from a statistical perspective which uses `R` and picks up right where this courses stops. This is based on the often referenced <a href="https://web.stanford.edu/~hastie/Papers/ESLII.pdf" target="_blank">*The Elements of Statistical Learning*</a> by Hastie, Tibshirani, and Friedman. Both are freely available online.

### Deep Learning

While, it probably isn't the best tool for the job, `R` now has the ability to <a href="https://rstudio.github.io/tensorflow/" target="_blank">train deep neural networks via TensorFlow</a>.

## Time Series

In this class we have only considered independent data. What if data is dependent? Time Series is the area of statistics which deals with this issue, and could easily span multiple courses.

Two books that are used in STAT 429 at the University of Illinois, both free:

- <a href="http://www.stat.pitt.edu/stoffer/tsa4/" target="_blank">*Time Series Analysis and Its Applications: With R Examples*</a> by Shumway and Stoffer
- <a href="http://tts.smac-group.com/" target="_blank">A Tour of Time Series Analysis with R</a> by Balamuta, Guerrier, Molinari, and Xu. This book is currently under development at UIUC.

Some tutorials:

- <a href="https://a-little-book-of-r-for-time-series.readthedocs.io/en/latest/" target="_blank">Little Book of R for Time Series</a>
- <a href="http://www.statmethods.net/advstats/timeseries.html" target="_blank">Quick `R`: Time Series and Forecasting</a>
- <a href="http://rpubs.com/ryankelly/ts6" target="_blank">TSA: Start to Finish Examples</a>

When performing time series analysis in `R` you should be aware of the <a href="https://cran.r-project.org/web/views/TimeSeries.html" target="_blank">many packages</a> that are useful for analysis. It should be hard to avoid the <a href="https://github.com/robjhyndman/forecast" target="_blank">`forecast`</a> and <a href="https://cran.r-project.org/web/packages/zoo/zoo.pdf" target="_blank">`zoo`</a> packages. Often the most difficult part will be dealing with time and date data. Make sure you are utilizing one of the many packages that help with this.

## Bayesianism

In this class, we have worked within the frequentist view of statistics. There is an entire alternative universe of Bayesian statistics.

<a href="https://sites.google.com/site/doingbayesiandataanalysis/" target="_blank">*Doing Bayesian Data Analysis: A Tutorial with R, JAGS, and Stan*</a> by John Kruschke is a great introduction to the topic. It introduces the world of <a href="https://www.cs.cornell.edu/Courses/cs4110/2016fa/lectures/lecture33.html" target="_blank">probabilistic programming</a>, in particular <a href="http://mc-stan.org/" target="_blank">Stan</a>, which can be used in both `R` and Python.

## High Performance Computing

Often `R` will be called a "slow" language, for two reasons. One, because many do not understand `R`. Two, because sometimes it really is. Luckily, it is easy to extend `R` via the <a href="http://www.rcpp.org/" target="_blank">`Rcpp` package</a> to allow for faster code. Many modern `R` packages utilize `Rcpp` to achieve better performance.

## Further `R` Resources

Also, don't forget that previously in this book we have outlined a large number of <a href="http://daviddalpiaz.github.io/appliedstats/introduction-to-r.html#r-resources" target="_blank">`R` resources</a>. Now that you've gotten started with `R` many of these will be much more useful.

If any of these topics interest you, and you would like more information, please don't hesitate to start a discussion on the forums!

:)
