# `R` Resources

So far, we have seen a lot of `R`, and a lot of `R` quickly. Again, the preceding chapters were in no way meant to be a complete reference for the `R` language, but rather an introduction to many of the concepts we will need in this text. The following resources are not necessary for the remainder of this text, but you may find them useful if you would like a deeper understanding of `R`:

## Beginner Tutorials and References

- [Try `R`](http://tryr.codeschool.com/) from Code School.
    - An interactive introduction to the basics of `R`. Useful for getting up to speed on `R`'s syntax.
- [Quick-R](http://www.statmethods.net/) by Robert Kabacoff.
    - A good reference for `R` basics.
- [`R` Tutorial](http://www.r-tutor.com/) by Chi Yau.
    - A combination reference and tutorial for `R` basics.
- [`R` Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/) by Roger Peng
    - A great text for `R` programming beginners. Discusses `R` from the ground up, highlighting programming details we might not discuss.

## Intermediate References

- [`R` for Data Science](http://r4ds.had.co.nz/) by Hadley Wickham and Garrett Grolemund.
    - Similar to Advanced `R`, but focuses more on data analysis, while still introducing programming concepts. Especially useful for working in the [tidyverse](http://tidyverse.org/). 
- [The Art of `R` Programming](https://www.nostarch.com/artofr.htm) by Norman Matloff.
    - Gentle introduction to the programming side of `R`. (Whereas we will focus more on the data analysis side.) A [free electronic version](http://vufind.carli.illinois.edu/vf-uiu/Record/uiu_6955421) is available through the Illinois library.

## Advanced References

- [Advanced `R`](http://adv-r.had.co.nz/) by Hadley Wickham.
    - From the author of several extremely popular `R` packages. Good follow-up to The Art of `R` Programming. (And more up-to-date material.)
- [The `R` Inferno](http://www.burns-stat.com/documents/books/the-r-inferno/) by Patrick Burns.
    - Likens learning the tricks of `R` to descending through the levels of hell. Very advanced material, but may be important if `R` becomes a part of your everyday toolkit.
- [Efficient `R` Programming](https://csgillespie.github.io/efficientR/) by Colin Gillespie and Robin Lovelace
    - Discusses both efficient `R` programs, as well as programming in `R` efficiently.


## RStudio and RMarkdown

The following videos were made as an introduction to `R`, RStudio, and RMarkdown for STAT 420 at UIUC. If you are currently using this text for a Coursera course, you can find updated videos there.

- [RStudio Basics](https://mediaspace.illinois.edu/media/%5BSTAT+420%5D+R+and+RStudio/1_ihjnvfis)
- [RMarkdown Intro](https://mediaspace.illinois.edu/media/%5BSTAT+420%5D+RMarkdown+Intro/1_36pkjkie)
- [RMarkdown Basics](https://mediaspace.illinois.edu/media/%5BSTAT+420%5D+RMarkdown+Basics/1_u0mk6uaq)
- [RMarkdown Tips and Tricks](https://mediaspace.illinois.edu/media/%5BSTAT+420%5D+RMarkdown+Tips+and+Tricks/1_ahkzbeka)

Note that RStudio and RMarkdown and constantly receiving excellent support and updates, so these videos already contain some outdated information. For example, as of recent RStudio versions, the "Import Dataset" functionality has been updated to utilize the [`readr`](https://github.com/tidyverse/readr) and [`tibble`](https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html) packages. Additionally, working interactively with RMarkdown documents in RStudio has a long list of new functionality.

[RStudio](http://rmarkdown.rstudio.com/) provides their own [tutorial for RMarkdown](http://rmarkdown.rstudio.com/lesson-1.html). They also have an excellent [RStudio "cheatsheets"](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf) which visually identifies many of the features available in the IDE.

## RMarkdown Template

[This `.zip` file](tutorial/rmd-template.zip) contains the files necessary to produce [this rendered document](tutorial/rmd-template.html). This document is a more complete version of a template than what is seen in the above videos.
