# Multiple Linear Linear Regression

> "Life is really simple, but we insist on making it complicated."
>
> --- **Confucius**

\[
Y_i = \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + \cdots + \beta_p X_{i(p-1)} + \epsilon_i, \qquad i = 1, 2, \ldots, n
\]

- TODO: note that $p$ is the number of $\beta$s. NOT ALL TEXTS do it this way.
- TODO: make some notational decisions.
- TODO: move matrix approach for SLR to SLR or SLR inf chapter?

\[
\mathbf{Y} = \mathbf{X} \beta + \epsilon
\]


\[
\mathbf{Y} = \begin{bmatrix} Y_1 \\ Y_2 \\ \cdots\\ Y_n \end{bmatrix}
\]


\[
\mathbf{\epsilon} = \begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \cdots\\ \epsilon_n \end{bmatrix}
\]



\[
\begin{bmatrix}
Y_1   \\
Y_2   \\
\cdots\\
Y_n   \\
\end{bmatrix}
=
\begin{bmatrix}
1      & x_1    \\
1      & x_2    \\
\cdots & \cdots \\
1      & x_n    \\
\end{bmatrix}
\begin{bmatrix}
\beta_0 \\
\beta_1 \\
\end{bmatrix}
+
\begin{bmatrix}
\epsilon_1   \\
\epsilon_2   \\
\cdots\\
\epsilon_n   \\
\end{bmatrix}
\]

\[
\mathbf{Y} = \mathbf{X} \mathbf{\beta} + \mathbf{\epsilon}
\]


\[
\hat{\mathbf{\beta}} = \left(  \mathbf{X}^T \mathbf{X}  \right)^{-1}\mathbf{X}^T \mathbf{Y}
\]

\[
E[\mathbf{\hat{\beta}}] = \mathbf{\beta} = \beta
\]

\[
Var[\mathbf{\hat{\beta}}] = \sigma^2 \left(  \mathbf{X}^T \mathbf{X}  \right)^{-1}
\]





stat significance vs practical significance, effect size
note about R2 interpretation in multiple setting
X matrix in R



## Introduction (Delete this Heading)

- Motive with examples with 2+ predictors
    - use uci cars
    - show brief cleaning steps
- show minimize f(beta) is LS
- do LS as matrix!


## Matrix Approach

## Sampling Distribution

### Confidence Intervals

### Confidence Intervals for Mean Response

### Prediction Intervals

## Single Parameter Tests

## Signifiance of Regression

## Nested Models

## Simulation



note about extrapolation.