# Beyond

> "End? No, the journey doesn't end here."
>
> --- **J.R.R. Tolkien**

After reading this chapter you will be able to:

- Understand the roadmap to continued education about models and the `R` programming language.

## What's Next

So you've completed STAT 420, where do you go from here? Now that you understand the basics of linear modeling, there is a wide world of applied statistics waiting to be explored. We'll briefly detail some courses in the [Statistics Department](http://www.stat.illinois.edu/) at the [University of Illinois at Urbana-Champaign](http://illinois.edu/) and discuss how they relate to what you have learned in STAT 420.

- STAT 425
    - further developement of regression
- STAT 424
    - ANOVA
- STAT 428
    - simulation, etc
    
- STAT 426
    - categorical response, models for explaination
    
- STAT 430, Statistical Learning
    - models for prediction
    - non-parameteric models.

- STAT 429
    - dependent data
    
## Further `R` Resources

- Tidyverse, Tidy Data