# Beyond

> "End? No, the journey doesn't end here."
>
> --- **J.R.R. Tolkien**

After reading this chapter you will be able to:

- Understand the roadmap to continued education about models and the `R` programming language.

## What's Next

So you've completed STAT 420, where do you go from here? Now that you understand the basics of linear modeling, there is a wide world of applied statistics waiting to be explored. We'll briefly detail some courses in the [Statistics Department](http://www.stat.illinois.edu/) at the [University of Illinois at Urbana-Champaign](http://illinois.edu/) and discuss how they relate to what you have learned in STAT 420.

- **STAT 385**, Statistics Programming Methods
    - This course will discuss computing theory from a statistical perspective by deeply studying the constructs of the *R* language.  The ideas behind how writing statistical algorithms like linear regression, given by `lm()`, and performing simulation studies at scale are emphasized.

- **STAT 425**, Applied Regression and Design
    - This course will discuss in further detail many of the methods discussed in this book, including proving some of the results we only verified via simulation. Will also discuss some aspects of experimental design.
    
- **STAT 424**, Analysis of Variance
    - This course will discuss ANOVA in greater detail, including one, two and multi-way ANOVA. It will also introduce fixed, random, and mixed effect models. There will also be considerable emphasis on the mathematics of linear models.

- **STAT 428**, Statistical Computing
    - This course will take a much deeper look into methods for simulation. There will be significant discussion of random number generation and Monte Carlo methods. How do those `rdist()` functions actually generate random observations?
    
- **STAT 426**, Sampling and Categorical Data
    - This course will discuss regression methods, however, instead of a numeric response, it will consider both categorical or discrete responses. To accomplish this task, it will introduce generalized linear models. Like this book, it will focus on models for explanation.

- **STAT 430**, Statistical Learning
    - This class is a machine learning course, from a statistical perspective. While in this text we have limited ourselves to linear models, which are good for explanation, this class will focus on models for prediction. As as result it will introduce several non-parametric methods. Each of regression, classification, and clustering will be considered. The wonderful textbook [An Introduction to Statistical Learning with Applications in `R`](http://www-bcf.usc.edu/~gareth/ISL/), which is freely available, is used.

- **STAT 429**, Time Series Analysis
    - This course will develop methods for modeling *dependent* data. One of the assumption of the linear models in this text have been the independence of the observations. This course will deal with the case when the observations are not independent. The book [Time Series Analysis and Its Applications: With `R` Examples](http://www.stat.pitt.edu/stoffer/tsa4/), which is freely available, is often used.
    
## Further `R` Resources

In this textbook, much of the data we have seen has been nice and tidy. It was rectangular where each row is an observation and each column is a variable. This is not always the case! Many packages have been developed to deal with data, and force it into a nice format, which is called [tidy data](http://vita.had.co.nz/papers/tidy-data.pdf), that we can then use for modeling. Often during analysis, this is where a large portion of your time will be spent.

The `R` community has started to call this collection of packages the Tidyverse. It was once called the Hadleyverse, as [Hadley Wickham](http://hadley.nz/) has authored so many of the packages. Hadley is writing a book called [`R` for Data Science](http://r4ds.had.co.nz/) which describes the use of many of these packages. (And also how to use some to make the modeling process better!) This book is a great starting point for diving deeper into the `R` community.

Also, don't forget that previously in this book we have outlined a large number of [`R` resources](http://daviddalpiaz.github.io/appliedstats/introduction-to-r.html#r-resources). Now that you've gotten started with `R` many of these will be much more useful.

.
