---
title: "Course Schedule, Ideas and Notes"
output: html_document
---

## Schedule

Introduction to Linear Models

- Week 1: `R`, Markdown, Simulation, Testing, Probability
- Week 2: SLR
- Week 3: SLR Inference, Matrix Approach
- Week 4: Correlation, MLR

Extending Linear Models

- Week 5: ANOVA and ANCOVA
- Week 6: Diagnostics and Transformations
- Week 7: Model Selection
- Week 8: Time Series

## Homework

### Homework One

> Hofstadter's Law: "It always takes longer than you expect, even when you take into account Hofstadter's Law."
>
> --- **Douglas Hofstadter**, Gödel, Escher, Bach: An Eternal Golden Braid

- Basic R
    - Vectors, subsetting, math/stat functions on vectors.
- Probability
    - p, d, q functions. (Discrete for d function example.)
- Write a Function
    - get_iqr
    - use quantiles
    - compare with IQR()
    - arbitrary difference of quantiles
        - default is IQR
        - exception handing?
            - check 0 < a < 1
            - check a < b
- Install a Package
    - boxplot
    - test
- Import Data
    - scatterplot
    - test?
- Simulation
    - N = ?
    - exp param = ?
    - n = 5, n = 50
    - exponential?
    - plot hist
    - functoin for arbitrary:
        - N
        - n
        - exp paramter

## Videos

- RStudio
    - Basic. Four panels.
    - Write into .R, run with keyboard shortcut.
- RMarkdown
    - read.csv
    - install.packages()
    - toc
    - folder structure (one per homework.)
    - post document made in video
    

## Ideas

## Misc Notes

- Post Alex's hypothesis testing review?
- Week 7 is light, and Week 8 is unneeded for undergrads, which gives time to work on projects.
- Project should be released by Week 5.
